### ISSUE TITLE
Question about semantic segmentation.

### ISSUE THREAD

**Issue by kaitolucifer** [facebookresearch/Mask2Former#179]
I' using a custom semantic segmentation dataset.
There are 5 categories used in annotation png files. 0 is background and 1~4 is stuff categories.
I'm using a config file with settings like below.
```
MODEL:
  META_ARCHITECTURE: "MaskFormer"
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 0 # background
    NUM_CLASSES: 5
...
```

And training was fine.
But when I use `VisualizationDemo` in `demo/predictor.py` to generate predictions and visualizations, I found that visualizations are wired. Category 1 contains both background and original category 1 areas.

The output predictions of model are `5xHxW` maps and I use `predictions["sem_seg"].argmax(dim=0)` to get a `HxW` map which every pixel suppose to be 0~4. But I found that there are no background category which is 0.
Does anyone know what went wrong?
